# Generated by Django 4.1.3 on 2022-11-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sate',
            new_name='state',
        ),
    ]
