# Generated by Django 4.1.3 on 2022-11-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_sate_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_category',
            field=models.CharField(choices=[('creator', 'creator'), ('regular', 'regular')], max_length=20),
        ),
    ]
